### PR TITLE
Changes time to steps 

### PR DESCRIPTION
**Pull request by sumith1896**
...and also modified Knapsack and RealTimeQueue for it, we can do the rest later.

@ravimad Could you have a look and merge?

### CODE REVIEW

**Comment by sumith1896** [comment]
05ad6e3 renames `withState` to `in`, `outState` to `outSt` and `inState` to `in`.

**Comment by sumith1896** [comment]
This PR is now complete, I'll move on to the rest. Cheers!

**Comment by ravimad** [comment]
Merged. Thanks

**Comment by sumith1896** [comment]
Cheers!

**Pull request merged**
