### PR TITLE
Automate running of benchmarks

### PR DESCRIPTION
**Pull request by sumith1896**

### CODE REVIEW

**Comment by Sumith1896** [comment]
@ravimad `kthMin` for k = 10
orbvsactualkthmintime10
orbvsactualkthmintime100
orbvsactualkthmintime1000

**Comment by sumith1896** [comment]
@ravimad The previous graphs were slightly inaccurate, the following are the correct ones
orbvsactualkthmintime10
orbvsactualkthmintime100
orbvsactualkthmintime1000

**Comment by Sumith1896** [comment]
For withinst vs ops
orbvsactualkthmintime10
orbvsactualkthmintime100
orbvsactualkthmintime1000

**Comment by Sumith1896** [comment]
For `SortingnConcat`
```
. ┌─────────┐
╔═╡ Summary ╞═════════════════════════════════════════════════════════════════════════════════════════╗
║ └─────────┘                                                                                         ║
║ concat-         time <= 7                                                                    0.841  ║
║ kthMin-         2 * time <= (41 * k + 30 * (k * l.list-mem-time(uiState)._1._1.size)) + 3    17.805 ║
║ pullMin-        time <= 15 * l.size + 2                                                      2.113  ║
║ sort-           time <= 15 * l.size + 10                                                     1.315  ║
╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
║ total: 4     inferred: 4     unknown: 0     time: 22.074                                            ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════╝
```
For `CyclicFibStream`:
```
Resource Verification Results: 
. ┌─────────┐
╔═╡ Summary ╞══════════════════════════════════════════════╗
║ └─────────┘                                              ║
║ genNext-        time <= 42                  1.079        ║
║ next-           time <= 71                  52.117       ║
║ nthElemAfterTh… time <= 80 * n + 1          0.967        ║
║ nthFib-         4 * time <= 351 * n + 20    3.086        ║
║ zipWithFun-     time <= 13                  0.465        ║
╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
║ total: 5     inferred: 5     unknown: 0     time: 57.714 ║
╚══════════════════════════════════════════════════════════╝
```
For `LazyNumericalRep`:
```
Resource Verification Results: 
. ┌─────────┐
╔═╡ Summary ╞═════════════════════════════════════════════╗
║ └─────────┘                                             ║
║ Pay-            time <= 52     0.777                    ║
║ inc-            time <= 43     1.146                    ║
║ incAndPay-      time <= 122    0.934                    ║
║ incLazy-        time <= 29     2.652                    ║
║ incNum-         time <= 56     0.271                    ║
╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
║ total: 5     inferred: 5     unknown: 0     time: 5.780 ║
╚═════════════════════════════════════════════════════════╝
```

**Comment by Sumith1896** [comment]
For `RealTimeQueue`:
```
Resource Verification Results: 
. ┌─────────┐
╔═╡ Summary ╞══════════════════════════════════════════════╗
║ └─────────┘                                              ║
║ dequeue-        time <= 71    14.287                     ║
║ enqueue-        time <= 39    1.761                      ║
║ rotate-         time <= 22    0.954                      ║
╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
║ total: 3     inferred: 3     unknown: 0     time: 17.002 ║
╚══════════════════════════════════════════════════════════╝
```

**Comment by sumith1896** [comment]
```
Resource Verification Results: 
. ┌─────────┐
╔═╡ Summary ╞═══════════════════════════════════════════════╗
║ └─────────┘                                               ║
║ cons-           time <= 528                 2.431         ║
║ createQueue-    time <= 181                 2.361         ║
║ drop-           time <= 16 * n + 2          0.956         ║
║ force-          time <= 165                 1.022         ║
║ forceTwice-     time <= 677                 3.035         ║
║ revAppend-      time <= 15 * l1.size + 2    2.071         ║
║ reverse-        time <= 7                   0.129         ║
║ rotateDrop-     time <= 149                 126.257       ║
║ rotateRev-      time <= 123                 5.279         ║
║ tail-           time <= 1055                1.726         ║
║ tailSub-        time <= 883                 3.225         ║
║ take-           time <= 18 * n + 3          0.965         ║
║ takeLazy-       time <= 17                  3.043         ║
╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
║ total: 13    inferred: 13    unknown: 0     time: 152.500 ║
╚═══════════════════════════════════════════════════════════╝
```

**Comment by sumith1896** [comment]
orbvsactualcons10
orbvsactualcons100
orbvsactualcons1000
orbvsactualreverse10
orbvsactualreverse100
orbvsactualreverse1000
orbvsactualtail10
orbvsactualtail100
orbvsactualtail1000

**Comment by sumith1896** [comment]
Captured all calls to rotateDrop and tailLazy  and plotted with orb predicted

rotatedroptimevsorb
takelazycountvsorb

**Comment by sumith1896** [comment]
dropvsorb
revappendvsorb
rotaterevvsorb

**Comment by sumith1896** [comment]
dropvsorb

**Comment by sumith1896** [comment]
dropvsorb

**Pull request merged**
