### PR TITLE
Fixing Viterbi algorithm

### PR DESCRIPTION
**Pull request by sumith1896**
Hi @ravimad,

The proof now works and goes through master.
The @ axiom needs to be proved, I'll do that tomorrow. I'll polish it up a bit more too. For now I'm glad it's working :)

### CODE REVIEW

**Comment by ravimad** [comment]
That is indeed great. Keep it up

**Comment by sumith1896** [comment]
@ravimad Works now. Could you try this out and merge?

**Comment by sumith1896** [comment]
@ravimad Could you merge this? I would like this in master

**Comment by sumith1896** [comment]
Thanks!

**Pull request merged**
