### PR TITLE
[WIP] Generating runnable code after instrumentation

### PR DESCRIPTION
**Pull request by sumith1896**
// not tested yet

### CODE REVIEW

**Comment by sumith1896** [comment]
`import`s have been just dumped, some may be unnecessary.

**Comment by sumith1896** [comment]
Using Orb for InsertionSort

```
. ┌─────────┐
╔═╡ Summary ╞═════════════════════════════════════════════════════════════════════════════╗
║ └─────────┘                                                                             ║
║ size            0 <= 4 * res + 1 && 0 <= res + 2                                  0.000 ║
║ sort            64 * time <= 703 * (size(l) * size(l)) + 192 && rec <= size(l)    1.279 ║
║ sortedIns       time <= 8 * size(l) + 4 && depth <= 3 * size(l) + 3               3.601 ║
╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
║ total: 3     inferred: 3     unknown: 0     time: 4.880                                 ║
╚═════════════════════════════════════════════════════════════════════════════════════════╝
```

(optional)

```
. ┌─────────┐
╔═╡ Summary ╞════════════════════════════════════════════════════════════════════════════════════╗
║ └─────────┘                                                                                    ║
║ size            0 <= 3 * res + 1 && 0 <= res + 1                                         0.000 ║
║ sort            time <= (4 * (size(l) * size(l)) + 6 * size(l)) + 3 && rec <= size(l)    1.717 ║
║ sortedIns       time <= 8 * size(l) + 4 && 2 * depth <= 7 * size(l) + 6                  2.676 ║
╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
║ total: 3     inferred: 3     unknown: 0     time: 4.393                                        ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by sumith1896** [comment]
Data from runnable code

```
10 337
20 1177
30 2063
40 4259
50 5954
60 8487
70 10453
80 13739
90 18962
100 24013
110 27908
120 31745
130 40439
140 47549
150 51083
160 54861
170 65878
180 71108
190 82917
200 87144
```

**Comment by sumith1896** [comment]
(stackoverflow for any n > 300)

**Comment by sumith1896** [comment]
Orb numbers

```
SET 1
10 1101.4375
20 4396.75
30 9888.9375
40 17578.0
50 27463.9375
60 39546.75
70 53826.4375
80 70303.0
90 88976.4375
100 109846.75
110 132913.9375
120 158178.0
130 185638.9375
140 215296.75
150 247151.4375
160 281203.0
170 317451.4375
180 355896.75
190 396538.9375
200 439378.0
SET 2
10 463
20 1723
30 3783
40 6643
50 10303
60 14763
70 20023
80 26083
90 32943
100 40603
110 49063
120 58323
130 68383
140 79243
150 90903
160 103363
170 116623
180 130683
190 145543
200 161203
```

**Comment by sumith1896** [comment]
ping @ravimad 
orbvsactual

**Comment by sumith1896** [comment]
Working out PropositionalLogic and trying to automate the process:

```
Inference Result: 
. ┌─────────┐
╔═╡ Summary ╞════════════════════════════════════════════════════╗
║ └─────────┘                                                    ║
║ isNNF           time <= 8 * size(f)                     2.404  ║
║ nnf             time + 17 <= 43 * size(formula)         18.161 ║
║ removeImplies   time + 3 <= 8 * size(f)                 0.510  ║
║ simplify        2 * time + 15 <= 35 * size(f)           1.708  ║
║ size            1 <= 2 * res && 1 <= res && 0 <= res    0.000  ║
╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
║ total: 5     inferred: 5     unknown: 0     time: 22.783       ║
╚════════════════════════════════════════════════════════════════╝
```

**Comment by sumith1896** [comment]
(https://github.com/sameersingh/scalaplot) works

**Comment by ravimad** [comment]
Great. try using this.

**Comment by sumith1896** [comment]
Will send in a fresh PR with cleaner commits

**Pull request closed without merging**
